### PR TITLE
Fix Issue #73: allow case-only filename changes; Fix Issue #77: thumbnail view to right or bottom

### PR DESCRIPTION
**Pull request by fire-eggs**

### CODE REVIEW

**Comment by fire-eggs** [comment]
I'm obviously still confused by pull requests. There are two bug fixes mashed together; I hoped to submit them separately.

Fixing issue 73 is straightforward.

To partially address issue 77, I have changes to allow the thumbnail view to appear on the right side or the bottom. The ImageListView component makes this easy; it is not feasible to attempt to have the thumbnail view on the _left_ side. 

I have attempted to add a new setting to support this capability. If I missed any required changes to various language packs, my apologies...

One limitation of the new feature is the thumbnail view must be turned off, then on again, to see the changed position of the thumbnails.

**Comment by d2phap** [comment]
Thanks @fire-eggs 

For issue #73: I tested on my machine, I still can rename it from Image.png to image.png.
So I left a comment there.

**Comment by fire-eggs** [comment]
Yes, most of the time I can also rename while making case-only changes. But I can make the reported problem occur with certain mapped drives. So I left a comment there with a workaround.

**Comment by d2phap** [comment]
Just clean up the code for thumbnail bar position and Fix minimum width for horizontal thumbnail
https://github.com/d2phap/ImageGlass/commit/0c3f73f5dd2a2bdf0858d937efc13fc0c0444458

- The next step is to allow user to resize horizontal thumbnail bar

**Comment by d2phap** [comment]
Merged to develop branch

**Pull request closed without merging**
