### PR TITLE
Issue #773 discussion applied to master branch

### PR DESCRIPTION
**Pull request by unquietwiki**
Needs to be branched off, until it can be merged with the current stuff in develop.

### CODE REVIEW

**Comment by unquietwiki** [comment]
@d2phap Thanks! 👍

**Comment by d2phap** [comment]
Thanks for your refactoring @unquietwiki

**Comment by unquietwiki** [comment]
@d2phap I'm giving things another look over to see if there's anything else I can do. Honestly, refactoring is low-hanging fruit, but I feel like done properly it can knock out a few bug reports.

**Comment by d2phap** [comment]
It's good when somebody can contribute by improving the code. ☺

**Comment by unquietwiki** [comment]
@d2phap I did find one more thing. Currently, if I do a build in Visual Studio; bin\Debug\DefaultTheme will have a **config.xml**, but not an **igtheme.xml**, as required by the code. This wasn't the behavior I was running into before.

**Comment by d2phap** [comment]
`config.xml` was changed to `igconfig.xml` in #783 
I forgot to rename it in `/Setup/Assets/DefaultTheme/` folder

**Pull request merged**
