### PR TITLE
Color Picker tool

### PR DESCRIPTION
**Pull request by ssambi**
A draft of a color picker tool. 
As proposed in [https://github.com/d2phap/ImageGlass/wiki/Color-picker](https://github.com/d2phap/ImageGlass/wiki/Color-picker), it's possible to open the color picker tool from the menu, or with a keyboard shortcut.
immagine

A tool window is opened and shows RGB and Hex values of the pixel hovered by the mouse cursor.
immagine

### CODE REVIEW

**Comment by ssambi** [comment]
What it's missing:
- change the mouse cursor with a picker icon
- saving colors on mouse click
- other color space conversions

**Comment by d2phap** [comment]
Thank you @ssambi

**Comment by ProgrammerAuditore** [comment]
igcmd.exe has problems with windows 10.
They should let the user choose how to edit their photos as the HoneyView program does. It is very good but very basic.

**Comment by ProgrammerAuditore** [comment]
igcmd.exe has problems with windows 10.
They should let the user choose how to edit their photos as the HoneyView program does. It is very good but very basic.

**Comment by d2phap** [comment]
@ProgrammerAuditore 

> igcmd.exe has problems with windows 10.

What's the problem you mean?

> They should let the user choose how to edit their photos as the HoneyView program does. It is very good but very basic.

Yes you can change the apps for editing in Settings dialog

**Pull request merged**
