### PR TITLE
Add a toggle for displaying the "loading" message while viewing images

### PR DESCRIPTION
**Pull request by ProfanedBane**
Found this really annoying while using the program so I decided for babby's first C# contribution I'd give making a toggle a bash.

Basically it just adds a checkbox to the "Image" settings tab that can enable or disable the displaying of the "Loading" message when the program is busy while scrolling through images.

No idea if it's worth adding to the main program but any feedback etc is appreciated, I'm rather new to C# stuff.

### CODE REVIEW

**Comment by fire-eggs** [comment]
Been travelling, just starting to catch up. I'll take a look at this soonish. Thank you for the pull request!

**Comment by ProfanedBane** [comment]
Thanks. I'm not even sure if it's worth adding into the full project it was just a little hack I made.

**Comment by fire-eggs** [comment]
Looks good EXCEPT the changes made in the designer. That cannot be accepted as-is.

**Comment by ProfanedBane** [comment]
I'll have a lookie at how to proper do that sometime in the next week or two since I'm a bit busy.

**Comment by fire-eggs** [comment]
Not casting any aspersions - I've been bit multiple times by it.  Finally wrote the [wiki](https://github.com/d2phap/ImageGlass/wiki/Using-the-Visual-Studio-Designer-to-modify-the-GUI) entry 'cause I kept forgetting.

**Comment by ProfanedBane** [comment]
Closing this for now, forgot all about it and don't really have the time to fix it up since it's such a small feature.

**Pull request closed without merging**
