### PR TITLE
Better mouse wheel usage (Issues #95, #110)

### PR DESCRIPTION
**Pull request by 0-0-0-0**
Implemented vertical/horizontal image scrolling using the mouse wheel.
Added customization for mouse wheel and its combinations with Ctrl/Shift/Alt keys.
Removed the "Use the mouse wheel to navigate images, hold CTRL for zooming" option.
The new settings are added to Russian language pack.

igsettings

### CODE REVIEW

**Comment by d2phap** [comment]
Thanks @0-0-0-0 for this PR!

**Comment by Keith94** [comment]
Looks interesting, can't wait to try it.

**Comment by d2phap** [comment]
This is targeted to ImageGlass v5, but you will be able to try it out in ImageGlass Moon build soon.
https://github.com/d2phap/ImageGlass/projects/2

**Comment by Keith94** [comment]
Good. How can I get a notification of new ImageGlass Moon builds?
Update checker doesn't seem to work that well.

image

**Comment by d2phap** [comment]
@Keith94 
The current Check For Update only check for the stable release.
I think I should add for Moon version checking as well.

**Comment by Keith94** [comment]
Good idea. :)
How often does it check for updates anyway? Once per day?

**Pull request merged**
